### ISSUE TITLE
Roadmap 2021

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#693]
_This is a living document. Check back for updates!_

## Goal

H2O Wave aims to be the quickest way to build beautiful, realtime, high-performance web apps and dashboards entirely in Python (and soon R) without using HTML, Javascript, or CSS.

Our roadmap this year focuses on production-readiness, ease of use, expanding our palette of cards/components, better integration with third-party libraries, and R language support.

The initiatives marked :microscope: require us to have a better understanding of the problem and potential solutions before committing to actual feature work. We continuously tune the plan based on research, feedback, and lessons learned from shipping each release.

#### Legend

| Icon | Status |
| ------------- | ------------- |
| :construction: | In Progress |
| :no_entry: | Blocked |
| :hourglass: | Not shipped |
| :balloon: | Shipped, Experimental |
| :muscle: | Stretch Goal |
| :microscope:  | Research |

###  Core

- [ ] :construction: **Security fixes.** Fix all known security issues; GA release. #294 
- [ ] :construction: **URI prefix / base URI.** Make it easier to deploy the Wave server behind proxies. #59 
- [ ] **Multi-worker.** Support pre-forking for better scalability. #277 
- [ ] :hourglass: **App database.** Bundle cross-compiled, networked SQLite with Wave.
- [ ] :microscope: **Selector API.** A simpler syntax to update existing content. #148 

### Cards/Components

- [ ] :balloon: Chat (Discussions)
- [ ] :balloon: Canvas (Whiteboard)
- [ ] :construction: Other (Approx 40 new cards)

### Extensions

- [ ] :balloon: **Machine Learning (WaveML).** Easily build and include AI/ML models in Wave apps. [Repo](https://github.com/h2oai/wave-ml).
- [ ] **Analytics.** Easily include search/ad-hoc visualization in Wave apps (Clickhouse integration). #18 

### Extensibility

- [ ] :microscope: Support loading and event-handling for arbitrary Javascript libraries. #297 
- [ ] :microscope: **Extension API (WaveX).** Publish mechanism for third-party Python+Javascript extensions to Wave. #35

### Themes

- [ ] :microscope: Make native plots theme-able. #664 
- [ ] **Official Themes.** Ship a dozen additional themes.
- [ ] :hourglass: **User-defined Themes.** Allow users to dynamically define and use themes. #604 

### WYSIWYG

- [ ] :balloon: **Page Editor.** Allow end-users to edit page content and use Wave for collaboration (wiki, chat, whiteboard, etc.)
- [ ] :hourglass: **IDE *Make*.** Browser-based Python live-coding environment for developing Wave apps. #278 

### Python Driver

- [ ] **Quick install.** `pip install` also installs Wave server. #250 
- [ ] **Quick start.** `wave init` sets up starter apps. #38 
- [ ] :hourglass: IDE / Code Snippets. #506 #561 

### R Driver

- [ ] :construction: **R Scripts.** Author realtime dashboards and reports using R. #612
- [ ] **R Apps.** Author interactive web apps using R. #15 
- [ ] :muscle: Get package into CRAN.

### Documentation

- [ ] **Showcase.** Expand into a comprehensive demo of what’s possible in Wave - all cards, all components.
- [ ] **Examples.** Make current examples more comprehensible, add new examples. #49
- [ ] **Tour.** Rework to use responsive layout; make it easier to use as an online reference.
- [ ] **Guide.** Expand documentation; rework confusing parts; include FAQs from past Q&A / discussions / Slack.

### QA

- [ ] :microscope: Improve front-end test coverage.
- [ ] Improve server test coverage.
- [ ] Improve Python driver test coverage.

## Disclaimer 

Any statement in this document that is not purely historical is considered a forward-looking statement. Forward-looking statements included in this document are based on information available as of the date they are made, and H2O.ai assumes no obligation to update any forward-looking statements. The forward-looking roadmap does not represent a commitment, guarantee, obligation or promise to deliver any feature, or to deliver any feature by any particular date, and is intended to outline the general development plans. Customers should not rely on this roadmap to make any purchasing decision.
