### ISSUE TITLE
Improve Showcase

### ISSUE THREAD

**Issue by lo5** [h2oai/wave#699]
Make the showcase app in `py/demo` similar in principle to the [Bootstrap](https://getbootstrap.com/docs/5.0/components/alerts/) docs - an app that serves three purposes:

1. An extensive showcase of what Wave is capable of.
2. A reference developers can use in addition to the the currrent "Tour" app ("How do I do that?").
3. (For contributors) - a development-time tool manually/visually test new cards/components or changes to existing ones. If we build up a comprehensive collection of every card/component variation, the next step would be to automate visual verification (based on #531).

**Tasks**
- [ ] Create one page per card (with all possible variations)
- [ ] Create one page per component (with all possible variations)
- [ ] Guide level docs
- [ ] :muscle: Compile and display code snippet into the page for copypasta convenience
